version: '3.8'

services:
  fake-news-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_AI_API_KEY=AIzaSyAMmyPGhsi1EZO1od1BLn2NeivF_YFVdTU
      - ADMIN_PASSWORD=admin123
      - DATABASE_URL=sqlite:///fake_news_db.sqlite
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./models:/app/models
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - fake-news-app
    restart: unless-stopped

volumes:
  data:
  uploads:
  models: